theme: minima
minima:
  date_format: "%b %-d, %Y"

# Localization
timezone: Europe/Madrid
lang: pt-BR
locale: pt_BR

show_excerpts: false

title: Espanha Dicas

description: > 
  Este repositÃ³rio tem como propÃ³sito reunir as dicas para brasileiros 
  vivendo na Espanha ğŸ‡ªğŸ‡¸

social_links:
  telegram: t.me/rrnazario
  

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
