version: "3.8"

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    image: rrnazario/espanha-dicas:latest
    working_dir: /srv/jekyll
    command: >-
      sh -c "jekyll build && \
             jekyll serve --host 0.0.0.0 \
                          --port 4000 \
                          --livereload \
                          --watch \
                          --incremental"
    volumes:
      - ./:/srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
